supported_sites:
  djinni:
    link_to_vacancies: 'asd'
  dou:
    link_to_vacancies: 'asd'
spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
  task:
    scheduling:
      pool:
        size: 2
